---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./mysore/dell/cu
  - ./bangalore/dell/du

# Apps of Apps
resources:

  # - 10-gemini.yaml
  - 10-gemini-cluster.yaml
  - 20-gemini-cluster-sriovconfig.yaml
  - 30-gemini-cluster-ptpconfig.yaml