---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  # Each SITE_ID is a different zone
  topology.kubernetes.io/zone: ran-cu-mysore-server-profile-cu-dell00

commonAnnotations:
 #argocd.argoproj.io/sync-wave: "20"
 argocd.argoproj.io/sync-options: Prune=false
 argocd.argoproj.io/compare-options: IgnoreExtraneous
# Apps of Apps
resources:
  - 40-gemini-cluster-mysore-dell-cu.yaml
  - 50-gemini-cluster-mysore-dell-cu-00-pre.yaml
  - 60-gemini-cluster-mysore-dell-cu-01-post.yaml
  - 70-gemini-cluster-mysore-dell-cu-02-virt.yaml
  - 80-gemini-cluster-mysore-dell-cu-02-settings.yaml
